/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-09-26 05:20:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.ten.dao.*;
import com.ten.user.*;

public final class choiceCou_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ten.user");
    _jspx_imports_packages.add("com.ten.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>学生选课信息管理系统-正在选课</title>\r\n");
      out.write("\t<link href=\"style_1.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("    <body>\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("\t<div class=\"title\"><p> 学生选课信息管理系统 </p></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t<div class=\"main_left\">\r\n");
      out.write("\t\t<div class=\"main_left_class00\"><img src=img/touxiang.png></div>\r\n");
      out.write("\t\t<div class=\"main_left_class01\"><a href=\"stu/choiceCou.jsp\">学生选课</a></div>\r\n");
      out.write("\t\t<div class=\"main_left_class02\"><a href=\"stu/showCou.jsp\">课程查询</a></div>\r\n");
      out.write("\t\t<div class=\"main_left_class03\"><a href=\"stu/stuInfo.jsp\">学籍信息</a></div>\r\n");
      out.write("\t\t<div class=\"main_left_class100\">\r\n");
      out.write("\t\t<input class=\"reset\" type=\"button\" value=\"注销\" onClick=\"window.location.href=('/Ten/servlet/serDoLogout')\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t");

		Student stu = null;
    	if(session.getAttribute("student")==null){
    		response.sendRedirect("/Ten/Login.jsp");
    	}else{
    		stu = (Student)session.getAttribute("student");
    	}
      out.write("\r\n");
      out.write("\t<div class=\"main_right\">\r\n");
      out.write("\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t<p>亲爱的");
      out.print( stu.getSname() );
      out.write("同学，下午好</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t<div class=\"function\"><p>[通知]选课系统已开放</p></div>\r\n");
      out.write("\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t<form action=\"servlet/serInsertSc\" method=\"post\">\r\n");
      out.write("\t\t\t");
Course cou = null;
  				DaoCou selectcou = new DaoCou();
  				List<Course> list = selectcou.selectCou();
  				Iterator<Course> it = list.iterator(); 
  			
      out.write("\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("  \t\t\t\t\t<tr><td></td></tr>\r\n");
      out.write("  \t\t\t\t\t<tr>\r\n");
      out.write("  \t\t\t\t\t\t<td>课程编号</td><td>课程名称</td><td>课程学分</td><td>选课</td>\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t</tr>\r\n");
      out.write("  \t\t\t\t\t");
 
  						while(it.hasNext()){
  							cou = it.next();
  							if(selectcou.cou_is_selected(stu.getSNo(), cou.getCNo()) == 1) {
  								it.remove();
  							}	
  						}
  						it = list.iterator();
  						while(it.hasNext()){
  						cou = it.next();

  						
      out.write("\r\n");
      out.write("  \t\t\t\t\t<tr>\r\n");
      out.write("  \t\t\t\t\t<td>");
      out.print( cou.getCNo() );
      out.write("</td>\r\n");
      out.write("  \t\t\t\t\t<td>");
      out.print( cou.getCname() );
      out.write("</td>\r\n");
      out.write("  \t\t\t\t\t<td>");
      out.print( cou.getCcredit() );
      out.write("</td>\r\n");
      out.write("  \t\t\t\t\t<td><input type=\"checkbox\" name=\"choiceCou\" value=\"");
      out.print( cou.getCNo());
      out.write("\" /> </td>\r\n");
      out.write("  \t\t\t\t\t</tr>\r\n");
      out.write("\t\t  \t\t\t");

  					}
     			
      out.write("\r\n");
      out.write("     \t\t\t<tr><td></td></tr><tr><td></td><td></td>\r\n");
      out.write("  \t\t\t\t\t<td><input class=\"sure\" type=\"submit\" value=\"确定\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"cancle\" type=\"reset\" value=\"取消\"></td>\r\n");
      out.write("  \t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
